### ISSUE TITLE
Showing exception when switching to recent app screen.

### ISSUE THREAD

**Issue by acsway878787** [Maxr1998/MaxLock#139]
Device: ASUS PadFone S
ROM: CM13
Problem Description: When switching from current using app to recent apps screen, the exception occurs. It may be a unimportant bug as it seems to be no negative effects.

Logcat:

> I/ActivityManager(25197): START u0 {act=com.android.systemui.recents.SHOW_RECENTS flg=0x10804000 cmp=com.android.systemui/.recents.RecentsActivity} from uid 10017 on display 0
E/Xposed  (25500): java.lang.NoSuchFieldError: com.android.systemui.recents.views.TaskViewThumbnail#mTask
E/Xposed  (25500): 	at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:116)
E/Xposed  (25500): 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:894)
E/Xposed  (25500): 	at de.Maxr1998.xposed.maxlock.hooks.SystemUI$1.afterHookedMethod(Unknown Source)
E/Xposed  (25500): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
E/Xposed  (25500): 	at com.android.systemui.recents.views.TaskViewThumbnail.rebindToTask(<Xposed>)
E/Xposed  (25500): 	at com.android.systemui.recents.views.TaskView.onTaskDataLoaded(TaskView.java:678)
E/Xposed  (25500): 	at com.android.systemui.recents.model.Task.notifyTaskDataLoaded(Task.java:206)
E/Xposed  (25500): 	at com.android.systemui.recents.model.RecentsTaskLoader.loadTaskData(RecentsTaskLoader.java:499)
E/Xposed  (25500): 	at com.android.systemui.recents.views.TaskStackView.prepareViewToLeavePool(TaskStackView.java:1312)
E/Xposed  (25500): 	at com.android.systemui.recents.views.TaskStackView.prepareViewToLeavePool(TaskStackView.java:1303)
E/Xposed  (25500): 	at com.android.systemui.recents.views.ViewPool.pickUpViewFromPool(ViewPool.java:75)
E/Xposed  (25500): 	at com.android.systemui.recents.views.TaskStackView.synchronizeStackViewsWithModel(TaskStackView.java:396)
E/Xposed  (25500): 	at com.android.systemui.recents.views.TaskStackView.onMeasure(TaskStackView.java:771)
E/Xposed  (25500): 	at android.view.View.measure(View.java:18799)
E/Xposed  (25500): 	at com.android.systemui.recents.views.RecentsView.onMeasure(RecentsView.java:355)
E/Xposed  (25500): 	at android.view.View.measure(View.java:18799)
E/Xposed  (25500): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/Xposed  (25500): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/Xposed  (25500): 	at android.view.View.measure(View.java:18799)
E/Xposed  (25500): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/Xposed  (25500): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/Xposed  (25500): 	at android.view.View.measure(View.java:18799)
E/Xposed  (25500): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/Xposed  (25500): 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1458)
E/Xposed  (25500): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:746)
E/Xposed  (25500): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
E/Xposed  (25500): 	at android.view.View.measure(View.java:18799)
E/Xposed  (25500): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
E/Xposed  (25500): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/Xposed  (25500): 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2899)
E/Xposed  (25500): 	at android.view.View.measure(View.java:18799)
E/Xposed  (25500): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2108)
E/Xposed  (25500): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1224)
E/Xposed  (25500): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1460)
E/Xposed  (25500): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1115)
E/Xposed  (25500): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6023)
E/Xposed  (25500): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
E/Xposed  (25500): 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
E/Xposed  (25500): 	at android.view.Choreographer.doFrame(Choreographer.java:606)
E/Xposed  (25500): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
E/Xposed  (25500): 	at android.os.Handler.handleCallback(Handler.java:739)
E/Xposed  (25500): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/Xposed  (25500): 	at android.os.Looper.loop(Looper.java:148)
E/Xposed  (25500): 	at android.app.ActivityThread.main(ActivityThread.java:5461)
E/Xposed  (25500): 	at java.lang.reflect.Method.invoke(Native Method)
E/Xposed  (25500): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/Xposed  (25500): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/Xposed  (25500): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by Maxr1998** [comment]
Do you have the latest version from Google Play installed (7.0.4)?
It's fixed in there.

**Comment by acsway878787** [comment]
Oh, I stayed at 7.0.2 because it's the latest version on Xposed repo.
I'll update it right away, thanks for your reply.
